main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('games/', views.GameList.as_view(), name='index'),
    path('games/<int:pk>/', views.GameDetail.as_view(), name='detail'),
    path('games/create/', views.GameCreate.as_view(), name='games_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='games_update'),
    path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='games_delete'),
    path('accessorys/', views.AccessoryList.as_view(), name='accessorys_index'),
    path('accessorys/<int:pk>/', views.AccessoryDetail.as_view(), name='accessorys_detail'),
    path('accessorys/create/', views.AccessoryCreate.as_view(), name='accessorys_create'),
    path('accessorys/<int:pk>/update', views.AccessoryUpdate.as_view(), name='accessorys_update'),
    path('accessorys/<int:pk>/delete', views.AccessoryDelete.as_view(), name='accessorys_delete'),
]

retrogamecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

SESSIONS = (
    ('1', 'Casual'),
    ('2', 'Competitive'),
    ('3', 'Multiplayer'),
)
class Accessory(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('accessory_detail', kwargs={'pk': self.id})

class Game(models.Model):
    title = models.CharField(max_length=100)
    console = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    year = models.IntegerField()
    accessories = models.ManyToManyField(Accessory)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.id})


class Playing(models.Model):
    date = models.DateField('playing date')
    session = models.CharField(
        max_length=1,
        choices=SESSIONS,
        default=SESSIONS[0][0]
    )

    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_session_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Playing

class PlayingForm(ModelForm):
    class Meta:
        model = Playing
        fields = ['date', 'session']

main_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Game, Accessory
from .forms import PlayingForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

class GameList(ListView):
    model = Game

class GameDetail(DetailView):
    model = Game

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['playing_form'] = PlayingForm()
        return context

class GameCreate(CreateView):
    model = Game
    fields = '__all__'

class GameUpdate(UpdateView):
    model = Game
    fields = ['console', 'description', 'year']

class GameDelete(DeleteView):
    model = Game
    success_url = '/games/'

class AccessoryList(ListView):
    model = Accessory

class AccessoryDetail(DetailView):
    model = Accessory

class AccessoryCreate(CreateView):
    model = Accessory
    fields = '__all__'

class AccessoryUpdate(UpdateView):
    model = Accessory
    fields = ['description']

class AccessoryDelete(DeleteView):
    model = Accessory
    success_url = '/accessories/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Retro Game Collector</h1>
    <hr />
    <p>Hire the Retro Game Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Retro Game Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;RetroGameCollector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'games_create' %}">Add A Game</a></li>
                    <li><a href="{% url 'index' %}">View All My Games</a></li>
                    <li><a href="{% url 'accessorys_create' %}">Add An Accessory</a></li>
                    <li><a href="{% url 'accessorys_index' %}">View All My Accessories</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2020 Retro Game Collector &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

    <h1>Home</h1>

{% endblock %}

main_app/templates/main_app/accessory_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Accessory</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'accessorys_detail' object.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/accessory_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Accessory Details</h1>
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ object.name }}</span>
    <p>Description: {{ object.description }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'accessorys_update' object.id %}">Edit</a>
    <a href="{% url 'accessorys_delete' object.id %}">Delete</a>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/accessory_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
        <h1>Add Accessory</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/accessory_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Games List</h1>
{% for object in object_list %}
  <div class="card">
    <a href="{% url 'accessorys_detail' object.id %}">
      <div class="card-content">
        <span class="card-title">{{ object.name }}</span>
        <p>Description: {{ object.description }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Game</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'detail' object.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/game_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Game Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ object.title }}</span>
        <p>Console: {{ object.console }}</p>
        <p>Description: {{ object.description }}</p>
        <p>Year: {{ object.year }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'games_update' object.id %}">Edit</a>
        <a href="{% url 'games_delete' object.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="" method="post">
      {% csrf_token %}
      {{ playing_form.as_p }}
      <input type="submit" value="Add Play Session" class="btn">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Session</th></tr>
      </thead>
      <tbody>
        {% for playing in game.playing_set.all %}
          <tr>
            <td>{{playing.date}}</td>
            <td>{{playing.get_session_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ game.title }}'s Accessories</h3>
  {% if game.accessories.count %}
    {% for accessory in game.accessories.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            The {{ accessory.name }}
          </span>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>No Accessories</h5>
  {% endif %}
  </div>
</div>
{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
        <h1>Add Game</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/game_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Games List</h1>
{% for object in object_list %}
  <div class="card">
    <a href="{% url 'detail' object.id %}">
      <div class="card-content">
        <span class="card-title">{{ object.title }}</span>
        <p>Console: {{ object.console }}</p>
        <p>Description: {{ object.description }}</p>
        <p>Year: {{ object.year }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}